### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by bluemix** [silnrsi/font-alkalami#1]
Hello dears;
thanks for your work first,
and second, I hope you can include a screenshot for this
typeface.
I've created one, if you want to use it directly:
<img width="490" alt="font-alkalami" src="https://user-images.githubusercontent.com/3332274/76491040-b2934500-643d-11ea-83c5-0ea93eb87eca.png">

Thanks.

**Comment by LornaSIL** [comment]
Thanks for your feedback. We have a lot of examples on the official font page where the font is distributed: http://software.sil.org/alkalami/
