### ISSUE TITLE
references folder doesn't contain version 1.2

### ISSUE THREAD

**Issue by munzirtaha** [silnrsi/font-alkalami#3]
I can only see old versions in the references folder. The latest version 1.2 is not available. It's also easier if you make the latest version available in its own folder so any one who clone the repository can sym-link to that folder. This applies to all your fonts.

TIA

**Comment by bobh0303** [comment]
Can you explain your use of the references folder? I.e., for what purpose are you symlinking to it?

**Comment by munzirtaha** [comment]
I just want to install the font in my system using git so I can keep it updated easily. I clone the repository, then I symlink like this:

`ln -sf /path/font-alkalami/references/Alkalami-Regular-1_002.ttf ~/.local/share/fonts/Alkalami-Regular.ttf`

**Comment by LornaSIL** [comment]
That folder is used for our font testing, so it is not a reliable way to get the latest version of the font.
I don't know if you can use our API, but this link will always give you the latest version of Alkalami:
https://wirl.api.sil.org/Alkalami

**Comment by munzirtaha** [comment]
Thanks, but all the fonts repositories I am aware of contains beside the code, the binary fonts, so why did you chose not to do that?

**Comment by LornaSIL** [comment]
We do releases on Github: https://github.com/silnrsi/font-alkalami/releases/tag/v1.200

**Comment by devosb** [comment]
Are you using Ubuntu? If so, you can install the latest font from http://packages.sil.org/ with the command `sudo apt install fonts-sil-alkalami`. The font package will be upgraded as new font releases are made. [Debian](https://packages.debian.org/search?keywords=fonts-sil-alkalami&searchon=names&suite=all&section=all) and [Ubuntu](https://packages.ubuntu.com/search?keywords=fonts-sil-alkalami&searchon=names&suite=all&section=all) already have this font packaged (same package name) although they may (or may not) have the latest font version, depending on which version of Debian or Ubuntu you are using.

**Comment by munzirtaha** [comment]
I am not using Ubuntu. I use Arch Linux. I know I can install from aur packages. In fact I am a packager myself.
e.g. Though I do package https://aur.archlinux.org/packages/ttf-amiri/ to help users but I prefer to clone https://github.com/alif-type/amiri because it allows me to git log and see the changes and more importantly to update to latest version that's not released yet.

**Comment by bobh0303** [comment]
Thanks for explaining how you want to get releases, however it’s safest to only use fonts that have been through our testing and release process. We regularly break (and fix) things as we improve the fonts and don’t want that process to affect users.
